// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {database} from '../models';
import {github} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {filewatcher} from '../models';
import {terminal} from '../models';
import {gitactivity} from '../models';
import {gitpanel} from '../models';
import {session} from '../models';

export function AICancel(arg1:string):Promise<void>;

export function AIListProviders():Promise<Array<ai.AIProvider>>;

export function AISetProvider(arg1:ai.AIProvider):Promise<void>;

export function AISetSessionState(arg1:string,arg2:ai.SessionState):Promise<void>;

export function AuthLogin(arg1:string):Promise<void>;

export function AuthLogout():Promise<void>;

export function BuildCustomStack(arg1:Record<string, string>):Promise<void>;

export function ClearTerminalSnapshots():Promise<void>;

export function CompleteOnboarding():Promise<void>;

export function CreateAgent(arg1:string,arg2:string):Promise<database.AgentSession>;

export function CreateAgentSession(arg1:number,arg2:string,arg3:string):Promise<database.AgentSession>;

export function CreateTerminal(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:number):Promise<string>;

export function CreateTerminalForAgent(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:number,arg6:number):Promise<string>;

export function CreateTerminalForAgentResume(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:number,arg7:number):Promise<string>;

export function CreateWorkspace(arg1:string):Promise<database.Workspace>;

export function DeleteAgent(arg1:number):Promise<void>;

export function DeleteAgentSession(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function DestroyTerminal(arg1:string):Promise<void>;

export function DockerDetectImage(arg1:string):Promise<string>;

export function DockerIsAvailable():Promise<boolean>;

export function GHClosePullRequest(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GHCreateBranch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<github.Branch>;

export function GHCreateComment(arg1:string,arg2:string,arg3:number,arg4:string):Promise<github.Comment>;

export function GHCreateInlineComment(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:number,arg7:string):Promise<github.Comment>;

export function GHCreateIssue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<github.Issue>;

export function GHCreatePullRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<github.PullRequest>;

export function GHCreateReview(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<github.Review>;

export function GHGetPullRequest(arg1:string,arg2:string,arg3:number):Promise<github.PullRequest>;

export function GHGetPullRequestDiff(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<github.Diff>;

export function GHInvalidateCache(arg1:string,arg2:string):Promise<void>;

export function GHListBranches(arg1:string,arg2:string):Promise<Array<github.Branch>>;

export function GHListComments(arg1:string,arg2:string,arg3:number):Promise<Array<github.Comment>>;

export function GHListIssues(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<github.Issue>>;

export function GHListPullRequests(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<github.PullRequest>>;

export function GHListRepositories():Promise<Array<github.Repository>>;

export function GHListReviews(arg1:string,arg2:string,arg3:number):Promise<Array<github.Review>>;

export function GHMergePullRequest(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function GHUpdateIssue(arg1:string,arg2:string,arg3:number,arg4:any,arg5:any,arg6:any):Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetAuthState():Promise<auth.AuthState>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetAvailableTerminalFonts():Promise<Array<string>>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetCustomStackTools():Promise<Record<string, string>>;

export function GetHydrationData():Promise<main.HydrationPayload>;

export function GetLastCommit(arg1:string):Promise<filewatcher.CommitInfo>;

export function GetLayoutState():Promise<string>;

export function GetRateLimitInfo():Promise<github.RateLimitInfo>;

export function GetStackBuildState():Promise<main.StackBuildState>;

export function GetTerminalSnapshots():Promise<Array<main.TerminalSnapshotDTO>>;

export function GetTerminals():Promise<Array<terminal.SessionInfo>>;

export function GetWorkspaceHistoryBuffer(arg1:number):Promise<Record<string, string>>;

export function GetWorkspacesWithAgents():Promise<Array<database.Workspace>>;

export function GitActivityClear():Promise<void>;

export function GitActivityCount():Promise<number>;

export function GitActivityDiscardFile(arg1:string,arg2:string):Promise<void>;

export function GitActivityGet(arg1:string):Promise<gitactivity.Event>;

export function GitActivityGetStagedDiff(arg1:string,arg2:string):Promise<string>;

export function GitActivityGetStagedFiles(arg1:string):Promise<Array<gitactivity.EventFile>>;

export function GitActivityList(arg1:number,arg2:string,arg3:string):Promise<Array<gitactivity.Event>>;

export function GitActivityUnstageFile(arg1:string,arg2:string):Promise<void>;

export function GitPanelAcceptOurs(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitPanelAcceptTheirs(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitPanelDiscardFile(arg1:string,arg2:string):Promise<void>;

export function GitPanelGetConflicts(arg1:string):Promise<Array<gitpanel.ConflictFileDTO>>;

export function GitPanelGetDiff(arg1:string,arg2:string,arg3:string,arg4:number):Promise<gitpanel.DiffDTO>;

export function GitPanelGetHistory(arg1:string,arg2:string,arg3:number,arg4:string):Promise<gitpanel.HistoryPageDTO>;

export function GitPanelGetStatus(arg1:string):Promise<gitpanel.StatusDTO>;

export function GitPanelOpenExternalMergeTool(arg1:string,arg2:string):Promise<void>;

export function GitPanelPreflight(arg1:string):Promise<gitpanel.PreflightResult>;

export function GitPanelStageFile(arg1:string,arg2:string):Promise<void>;

export function GitPanelStagePatch(arg1:string,arg2:string):Promise<void>;

export function GitPanelUnstageFile(arg1:string,arg2:string):Promise<void>;

export function GitPanelUnstagePatch(arg1:string,arg2:string):Promise<void>;

export function HandleDeepLink(arg1:string):Promise<void>;

export function IsTerminalAlive(arg1:string):Promise<boolean>;

export function ListAgents():Promise<Array<database.AgentSession>>;

export function MoveAgentSessionToWorkspace(arg1:number,arg2:number):Promise<database.AgentSession>;

export function RenameWorkspace(arg1:number,arg2:string):Promise<database.Workspace>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveAgentLayout(arg1:number,arg2:string):Promise<void>;

export function SaveDefaultShell(arg1:string):Promise<void>;

export function SaveLanguage(arg1:string):Promise<void>;

export function SaveLayoutState(arg1:string):Promise<void>;

export function SaveShortcutBindings(arg1:string):Promise<void>;

export function SaveTerminalCursorStyle(arg1:string):Promise<void>;

export function SaveTerminalFontFamily(arg1:string):Promise<void>;

export function SaveTerminalFontSize(arg1:number):Promise<void>;

export function SaveTerminalSnapshots(arg1:Array<main.TerminalSnapshotDTO>):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SessionApproveGuest(arg1:string,arg2:string):Promise<void>;

export function SessionCreate(arg1:number,arg2:string,arg3:boolean,arg4:number):Promise<session.Session>;

export function SessionEnd(arg1:string):Promise<void>;

export function SessionGetActive():Promise<session.Session>;

export function SessionGetAuditLogs(arg1:string,arg2:number):Promise<Array<database.AuditLog>>;

export function SessionGetICEServers():Promise<Array<session.ICEServerConfig>>;

export function SessionGetJoinSecurityMetrics():Promise<session.JoinSecurityMetrics>;

export function SessionGetSession(arg1:string):Promise<session.Session>;

export function SessionGetSignalingURL():Promise<string>;

export function SessionJoin(arg1:string,arg2:string,arg3:string):Promise<session.JoinResult>;

export function SessionKickGuest(arg1:string,arg2:string):Promise<void>;

export function SessionListPendingGuests(arg1:string):Promise<Array<session.GuestRequest>>;

export function SessionRegenerateCode(arg1:string):Promise<session.Session>;

export function SessionRejectGuest(arg1:string,arg2:string):Promise<void>;

export function SessionRestartEnvironment(arg1:string):Promise<void>;

export function SessionRevokeCode(arg1:string):Promise<session.Session>;

export function SessionSetAllowNewJoins(arg1:string,arg2:boolean):Promise<session.Session>;

export function SessionSetGuestPermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveWorkspace(arg1:number):Promise<void>;

export function SetPollingContext(arg1:string):Promise<void>;

export function SetWorkspaceColor(arg1:number,arg2:string):Promise<database.Workspace>;

export function StartPolling(arg1:string,arg2:string):Promise<void>;

export function StopPolling():Promise<void>;

export function SyncGuestWorkspace(arg1:string):Promise<database.Workspace>;

export function UnwatchProject(arg1:string):Promise<void>;

export function WatchProject(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteTerminalAsGuest(arg1:string,arg2:string,arg3:string):Promise<void>;
