// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICancel(arg1) {
  return window['go']['main']['App']['AICancel'](arg1);
}

export function AIListProviders() {
  return window['go']['main']['App']['AIListProviders']();
}

export function AISetProvider(arg1) {
  return window['go']['main']['App']['AISetProvider'](arg1);
}

export function AISetSessionState(arg1, arg2) {
  return window['go']['main']['App']['AISetSessionState'](arg1, arg2);
}

export function AuthLogin(arg1) {
  return window['go']['main']['App']['AuthLogin'](arg1);
}

export function AuthLogout() {
  return window['go']['main']['App']['AuthLogout']();
}

export function BuildCustomStack(arg1) {
  return window['go']['main']['App']['BuildCustomStack'](arg1);
}

export function ClearTerminalSnapshots() {
  return window['go']['main']['App']['ClearTerminalSnapshots']();
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function CreateAgent(arg1, arg2) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2);
}

export function CreateAgentSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAgentSession'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTerminalForAgent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTerminalForAgent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTerminalForAgentResume(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateTerminalForAgentResume'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DestroyTerminal(arg1) {
  return window['go']['main']['App']['DestroyTerminal'](arg1);
}

export function DockerDetectImage(arg1) {
  return window['go']['main']['App']['DockerDetectImage'](arg1);
}

export function DockerIsAvailable() {
  return window['go']['main']['App']['DockerIsAvailable']();
}

export function GHClosePullRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['GHClosePullRequest'](arg1, arg2, arg3);
}

export function GHCreateBranch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHCreateBranch'](arg1, arg2, arg3, arg4);
}

export function GHCreateComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHCreateComment'](arg1, arg2, arg3, arg4);
}

export function GHCreateInlineComment(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GHCreateInlineComment'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GHCreateIssue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHCreateIssue'](arg1, arg2, arg3, arg4);
}

export function GHCreatePullRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GHCreatePullRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GHCreateReview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GHCreateReview'](arg1, arg2, arg3, arg4, arg5);
}

export function GHGetPullRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['GHGetPullRequest'](arg1, arg2, arg3);
}

export function GHGetPullRequestDiff(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GHGetPullRequestDiff'](arg1, arg2, arg3, arg4, arg5);
}

export function GHInvalidateCache(arg1, arg2) {
  return window['go']['main']['App']['GHInvalidateCache'](arg1, arg2);
}

export function GHListBranches(arg1, arg2) {
  return window['go']['main']['App']['GHListBranches'](arg1, arg2);
}

export function GHListComments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GHListComments'](arg1, arg2, arg3);
}

export function GHListIssues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHListIssues'](arg1, arg2, arg3, arg4);
}

export function GHListPullRequests(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHListPullRequests'](arg1, arg2, arg3, arg4);
}

export function GHListRepositories() {
  return window['go']['main']['App']['GHListRepositories']();
}

export function GHListReviews(arg1, arg2, arg3) {
  return window['go']['main']['App']['GHListReviews'](arg1, arg2, arg3);
}

export function GHMergePullRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GHMergePullRequest'](arg1, arg2, arg3, arg4);
}

export function GHUpdateIssue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GHUpdateIssue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetAvailableTerminalFonts() {
  return window['go']['main']['App']['GetAvailableTerminalFonts']();
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetCustomStackTools() {
  return window['go']['main']['App']['GetCustomStackTools']();
}

export function GetHydrationData() {
  return window['go']['main']['App']['GetHydrationData']();
}

export function GetLastCommit(arg1) {
  return window['go']['main']['App']['GetLastCommit'](arg1);
}

export function GetLayoutState() {
  return window['go']['main']['App']['GetLayoutState']();
}

export function GetRateLimitInfo() {
  return window['go']['main']['App']['GetRateLimitInfo']();
}

export function GetStackBuildState() {
  return window['go']['main']['App']['GetStackBuildState']();
}

export function GetTerminalSnapshots() {
  return window['go']['main']['App']['GetTerminalSnapshots']();
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function GetWorkspaceHistoryBuffer(arg1) {
  return window['go']['main']['App']['GetWorkspaceHistoryBuffer'](arg1);
}

export function GetWorkspacesWithAgents() {
  return window['go']['main']['App']['GetWorkspacesWithAgents']();
}

export function GitActivityClear() {
  return window['go']['main']['App']['GitActivityClear']();
}

export function GitActivityCount() {
  return window['go']['main']['App']['GitActivityCount']();
}

export function GitActivityDiscardFile(arg1, arg2) {
  return window['go']['main']['App']['GitActivityDiscardFile'](arg1, arg2);
}

export function GitActivityGet(arg1) {
  return window['go']['main']['App']['GitActivityGet'](arg1);
}

export function GitActivityGetStagedDiff(arg1, arg2) {
  return window['go']['main']['App']['GitActivityGetStagedDiff'](arg1, arg2);
}

export function GitActivityGetStagedFiles(arg1) {
  return window['go']['main']['App']['GitActivityGetStagedFiles'](arg1);
}

export function GitActivityList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitActivityList'](arg1, arg2, arg3);
}

export function GitActivityUnstageFile(arg1, arg2) {
  return window['go']['main']['App']['GitActivityUnstageFile'](arg1, arg2);
}

export function GitPanelAcceptOurs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPanelAcceptOurs'](arg1, arg2, arg3);
}

export function GitPanelAcceptTheirs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPanelAcceptTheirs'](arg1, arg2, arg3);
}

export function GitPanelDiscardFile(arg1, arg2) {
  return window['go']['main']['App']['GitPanelDiscardFile'](arg1, arg2);
}

export function GitPanelGetConflicts(arg1) {
  return window['go']['main']['App']['GitPanelGetConflicts'](arg1);
}

export function GitPanelGetDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPanelGetDiff'](arg1, arg2, arg3, arg4);
}

export function GitPanelGetHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPanelGetHistory'](arg1, arg2, arg3, arg4);
}

export function GitPanelGetStatus(arg1) {
  return window['go']['main']['App']['GitPanelGetStatus'](arg1);
}

export function GitPanelOpenExternalMergeTool(arg1, arg2) {
  return window['go']['main']['App']['GitPanelOpenExternalMergeTool'](arg1, arg2);
}

export function GitPanelPickRepositoryDirectory(arg1) {
  return window['go']['main']['App']['GitPanelPickRepositoryDirectory'](arg1);
}

export function GitPanelPreflight(arg1) {
  return window['go']['main']['App']['GitPanelPreflight'](arg1);
}

export function GitPanelStageFile(arg1, arg2) {
  return window['go']['main']['App']['GitPanelStageFile'](arg1, arg2);
}

export function GitPanelStagePatch(arg1, arg2) {
  return window['go']['main']['App']['GitPanelStagePatch'](arg1, arg2);
}

export function GitPanelUnstageFile(arg1, arg2) {
  return window['go']['main']['App']['GitPanelUnstageFile'](arg1, arg2);
}

export function GitPanelUnstagePatch(arg1, arg2) {
  return window['go']['main']['App']['GitPanelUnstagePatch'](arg1, arg2);
}

export function HandleDeepLink(arg1) {
  return window['go']['main']['App']['HandleDeepLink'](arg1);
}

export function IsTerminalAlive(arg1) {
  return window['go']['main']['App']['IsTerminalAlive'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function MoveAgentSessionToWorkspace(arg1, arg2) {
  return window['go']['main']['App']['MoveAgentSessionToWorkspace'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveAgentLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveAgentLayout'](arg1, arg2);
}

export function SaveDefaultShell(arg1) {
  return window['go']['main']['App']['SaveDefaultShell'](arg1);
}

export function SaveLanguage(arg1) {
  return window['go']['main']['App']['SaveLanguage'](arg1);
}

export function SaveLayoutState(arg1) {
  return window['go']['main']['App']['SaveLayoutState'](arg1);
}

export function SaveShortcutBindings(arg1) {
  return window['go']['main']['App']['SaveShortcutBindings'](arg1);
}

export function SaveTerminalCursorStyle(arg1) {
  return window['go']['main']['App']['SaveTerminalCursorStyle'](arg1);
}

export function SaveTerminalFontFamily(arg1) {
  return window['go']['main']['App']['SaveTerminalFontFamily'](arg1);
}

export function SaveTerminalFontSize(arg1) {
  return window['go']['main']['App']['SaveTerminalFontSize'](arg1);
}

export function SaveTerminalSnapshots(arg1) {
  return window['go']['main']['App']['SaveTerminalSnapshots'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SessionApproveGuest(arg1, arg2) {
  return window['go']['main']['App']['SessionApproveGuest'](arg1, arg2);
}

export function SessionCreate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SessionCreate'](arg1, arg2, arg3, arg4);
}

export function SessionEnd(arg1) {
  return window['go']['main']['App']['SessionEnd'](arg1);
}

export function SessionGetActive() {
  return window['go']['main']['App']['SessionGetActive']();
}

export function SessionGetAuditLogs(arg1, arg2) {
  return window['go']['main']['App']['SessionGetAuditLogs'](arg1, arg2);
}

export function SessionGetICEServers() {
  return window['go']['main']['App']['SessionGetICEServers']();
}

export function SessionGetJoinSecurityMetrics() {
  return window['go']['main']['App']['SessionGetJoinSecurityMetrics']();
}

export function SessionGetSession(arg1) {
  return window['go']['main']['App']['SessionGetSession'](arg1);
}

export function SessionGetSignalingURL() {
  return window['go']['main']['App']['SessionGetSignalingURL']();
}

export function SessionJoin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionJoin'](arg1, arg2, arg3);
}

export function SessionKickGuest(arg1, arg2) {
  return window['go']['main']['App']['SessionKickGuest'](arg1, arg2);
}

export function SessionListPendingGuests(arg1) {
  return window['go']['main']['App']['SessionListPendingGuests'](arg1);
}

export function SessionRegenerateCode(arg1) {
  return window['go']['main']['App']['SessionRegenerateCode'](arg1);
}

export function SessionRejectGuest(arg1, arg2) {
  return window['go']['main']['App']['SessionRejectGuest'](arg1, arg2);
}

export function SessionRestartEnvironment(arg1) {
  return window['go']['main']['App']['SessionRestartEnvironment'](arg1);
}

export function SessionRevokeCode(arg1) {
  return window['go']['main']['App']['SessionRevokeCode'](arg1);
}

export function SessionSetAllowNewJoins(arg1, arg2) {
  return window['go']['main']['App']['SessionSetAllowNewJoins'](arg1, arg2);
}

export function SessionSetGuestPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionSetGuestPermission'](arg1, arg2, arg3);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetPollingContext(arg1) {
  return window['go']['main']['App']['SetPollingContext'](arg1);
}

export function SetWorkspaceColor(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceColor'](arg1, arg2);
}

export function StartPolling(arg1, arg2) {
  return window['go']['main']['App']['StartPolling'](arg1, arg2);
}

export function StopPolling() {
  return window['go']['main']['App']['StopPolling']();
}

export function SyncGuestWorkspace(arg1) {
  return window['go']['main']['App']['SyncGuestWorkspace'](arg1);
}

export function UnwatchProject(arg1) {
  return window['go']['main']['App']['UnwatchProject'](arg1);
}

export function WatchProject(arg1) {
  return window['go']['main']['App']['WatchProject'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}

export function WriteTerminalAsGuest(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTerminalAsGuest'](arg1, arg2, arg3);
}
